{
 "title": "Votingapp",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU_usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$D/($E/100)", "type": "math" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B*100", "type": "math" }
   ]
  },
  {
   "title": "Voteapp_logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"voteapp\"} |= ``"
    }
   ]
  }
 ]
}